spring:
  application:
    name: wisdomBI-backend
  devtools:
    restart:
      enabled: false
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
     store-type: redis
    # 30 天过期
     timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wisdomBI
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 3
    host: 192.168.15.131
    port: 6379
    password: 123...
    timeout: 5000
    lettuce:
      pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10  # 连接池中最大空闲连接
        min-idle: 1  # 连接池中最小空闲连接
        time-between-eviction-runs: 10s
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  rabbitmq:
    host: 192.168.15.131 # 虚拟机IP
    port: 5672 # 端口
    virtual-host: /bi # 虚拟主机
    username: wisdomBI # 用户名
    password: 123... # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能处理一个消息
        acknowledge-mode: manual # 自动确认消息，有失败重试，下面配置重试的次数
        retry:
          enabled: true #关闭，采用死信队列；开启消费者失败重试 (下面的可以不加，如果不改，次数默认3次）
          initial-interval: 1000ms #初始的失败等待时长为1秒
          multiplier: 1 #下次失败的等待时长倍数，下次等待时长=multiplier*last-interval
          max-attempts: 2 #最大重试次数
          stateless: true #true无状态，：false有状态。如果业务中包含事务，这里改为false
server:
  address: 0.0.0.0 # 本地开发，为了前端使用openapi生成接口，不要使用localhost，不然访问不到
  port: 8088
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 关闭驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
#aliyun:
#  oss:
#    endpoint: xxx
#    accessKeyId: xxx
#    accessKeySecret: xxx
#    bucketName: xxx
#  sms:
#    accessKeyId: xxx
#    accessKeySecret: xxx
#    signName: xxx  #签名名称
#    templateCode: xxx #短信模板信息
#    endpoint: xxx

# 智普AI
ai:
  apiKey: xxx  # 通用APIkey (包含了id 和 secret）